 ![Image.png](Image/Image.png)

### Part 1: Import Libraries and Dataset

In [19]:
# import Libaries & Packages
import numpy as np                  # Import Numpy for data statistical analysis
import pandas as pd                 # Import Pandas for data manipulation using dataframes
import seaborn as sns               # Statistical data visualization
import matplotlib.pyplot as plt     # Import matplotlib for data visualisation

In [20]:
# Import Youtube Ham or Spam dataset taken from UCI
df1 = pd.read_csv("dataset/Youtube01-Psy.csv")              # Psy youtube channel most viewed video comments dataset
df2 = pd.read_csv("dataset/Youtube02-KatyPerry.csv")        # KatyPerry youtube channel most viewed video comments dataset
df3 = pd.read_csv("dataset/Youtube03-LMFAO.csv")            # Psy LMFAO channel most viewed video comments dataset
df4 = pd.read_csv("dataset/Youtube04-Eminem.csv")           # Eminem youtube channel most viewed video comments dataset
df5 = pd.read_csv("dataset/Youtube05-Shakira.csv")          # Shakira youtube channel most viewed video comments dataset

In [21]:
# Merge all the datasset into single file
frames = [df1,df2,df3,df4,df5]                          # make a list of all file
df_merged = pd.concat(frames)                           # concatenate the all the file into single
keys = ["Psy","KatyPerry","LMFAO","Eminem","Shakira"]   # Merging with Keys
df_with_keys = pd.concat(frames,keys=keys)              # concatenate data with keys
dataset=df_with_keys

In [22]:
# Infomation about dataset
print(dataset.size)                 # size of dataset
print(dataset.shape)                # shape of datadet
print(dataset.keys())               # attributes of dataset
print(dataset.info())               # information about dataset

9780
(1956, 5)
Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1956 entries, (Psy, 0) to (Shakira, 369)
Data columns (total 5 columns):
COMMENT_ID    1956 non-null object
AUTHOR        1956 non-null object
DATE          1711 non-null object
CONTENT       1956 non-null object
CLASS         1956 non-null int64
dtypes: int64(1), object(4)
memory usage: 85.7+ KB
None


### Part 2: Data Preprocessing

In [23]:
# working with text content
dataset = dataset[["CONTENT" , "CLASS"]]             # context = comments of viewers & Class = ham or Spam

In [24]:
# Predictor and Target attribute
dataset_X = dataset['CONTENT']                       # predictor attribute
dataset_y = dataset['CLASS']                         # target attribute

In [25]:
# Feature Extraction from Text using  TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer   # import TF-IDF model from scikit Learn

In [26]:
# Extract Feature With TF-IDF model 
corpus = dataset_X                               # declare the variable
cv = TfidfVectorizer()                           # initialize the TF-IDF  model
X = cv.fit_transform(corpus).toarray()           # fit the corpus data into BOW model
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
# Split the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, dataset_y, test_size=0.2, random_state=0)

In [28]:
# shape of predictor attrbute after Extract Features
X.shape

(1956, 4454)

In [29]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [30]:
max_review_length = 4454
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [32]:
X_train.shape

(1564, 4454)

In [33]:
# create the model
embedding_vecor_length = 256
top_words = 5000
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(500))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4454, 256)         1280000   
_________________________________________________________________
lstm_1 (LSTM)                (None, 500)               1514000   
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 501       
Total params: 2,794,501
Trainable params: 2,794,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1, batch_size=64)

Instructions for updating:
Use tf.cast instead.
Train on 1564 samples, validate on 392 samples
Epoch 1/1


### Part 3: Building a Model

In [14]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7)

In [15]:
# load the dataset but only keep the top n words, zero the rest
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)

In [16]:
X_train.shape

(25000,)

In [32]:
# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [35]:
X_train.shape

(25000, 500)

In [37]:
# create the model
embedding_vecor_length = 32
model = Sequential()


In [ ]:
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

### Part 4: Making a Prediction and Evaluate the Result

In [105]:
# predict the result
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)               # probability above 50 considered 1 and below 50 considered 0

In [106]:
# Making a Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix= confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#[row, column]
TP = confusion_matrix[1, 1]        
TN = confusion_matrix[0, 0]           
FP = confusion_matrix[0, 1]           
FN = confusion_matrix[1, 0]

[[172  11]
 [  9 200]]


In [107]:
# Evaluate the Result
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_absolute_error, roc_auc_score
 
# Accuracy Score 
print('Accuracy Score:', accuracy_score(y_test, y_pred)) 

# Precision Score
print('Precision Score:', precision_score(y_test, y_pred))   

# True positive Rate (TPR) or Sensitivity or Recall    
print('True positive Rate:', recall_score(y_test, y_pred))             

# False positive Rate (FPR)
print('False positive Rate', FP / float(TN + FP))                       

# F1 Score or F-Measure or F-Score
print('F1 Score:', f1_score(y_test, y_pred))                 

# Specificity
print('Specificity:', TN / (TN + FP))                    

# Mean Absolute Error
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))   

# ROC Area
print('ROC Area:', roc_auc_score(y_test, y_pred)) 

Accuracy Score: 0.9489795918367347
Precision Score: 0.9478672985781991
True positive Rate: 0.9569377990430622
False positive Rate 0.060109289617486336
F1 Score: 0.9523809523809523
Specificity: 0.9398907103825137
Mean Absolute Error: 0.05102040816326531
ROC Area: 0.9484142547127881


### Part 5: Save, Load and Used this Model

In [108]:
# import pickle library 
import pickle               # pickle used for serializing and de-serializing a Python object structure

In [109]:
# save the model
Multilayer_Perceptron = open("Multilayer Perceptron.pkl","wb")          # open the file for writing
pickle.dump(classifier,Multilayer_Perceptron)                           # dumps an object to a file object
Multilayer_Perceptron.close()                                           # here we close the fileObject

In [110]:
# Load the model
ytb_model = open("Multilayer Perceptron.pkl","rb")           # open the file for reading
new_model = pickle.load(ytb_model)                           # load the object from the file into new_model
new_model

In [111]:
# Used the model for Prediction
comment = ["Hey Music Fans I really appreciate all of you,but see this song too"]
vect = cv.transform(comment).toarray()
new_model.predict(vect)

array([[0.9998117]], dtype=float32)

In [112]:
if new_model.predict(vect) == 1:
    print("Spam")
else:
    print("Ham")

Ham


#### for any query: amirali.cheema@outlook.com